name: Release and Publish

# 触发条件：推送 tag
on:
  push:
    tags:
      - 'v*.*.*'  # 匹配语义化版本标签

jobs:
  release:
    name: Build, Test and Release
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # 创建 release
      id-token: write  # NPM 发布

    steps:
      # 1. 检出代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. 设置 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.1

      # 3. 设置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      # 4. 安装依赖和构建
      - name: Install and Build
        run: |
          pnpm install
          pnpm run lint
          pnpm run build

      # 5. 获取版本信息
      - name: Get version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          TAG=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      # 6. 创建发布包
      - name: Create release archive
        run: |
          mkdir -p release-temp
          cp -r dist package.json README.md release-temp/
          cd release-temp && tar -czf ../ccman-${{ steps.version.outputs.tag }}.tar.gz .

      # 7. 发布到 NPM
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public

      # 8. 创建 GitHub Release  
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "CCMan ${{ steps.version.outputs.tag }}"
          body: |
            ## CCMan (Claude Code Manager) ${{ steps.version.outputs.tag }}

            🚀 **新版本发布！**

            ### 📦 安装方式
            ```bash
            npm install -g ccman@${{ steps.version.outputs.version }}
            ```

            ### 🔗 相关链接
            - [NPM 包](https://www.npmjs.com/package/ccman)
            - [GitHub 仓库](https://github.com/${{ github.repository }})

            ### 📋 发布信息
            - **提交哈希**: ${{ github.sha }}
            - **构建环境**: GitHub Actions

            ---
            *通过 GitHub Actions 自动构建发布*
          files: |
            ccman-*.tar.gz
          draft: false
          prerelease: ${{ contains(github.ref, '-beta') || contains(github.ref, '-alpha') || contains(github.ref, '-rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}